name: Daily Newsletter
on:
  schedule:
    - cron: "15 11 * * *"   # 07:15 America/New_York (11:15 UTC)
  workflow_dispatch:

# allow this workflow to push commits (for the archive files in /out)
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (debug on)
        env:
          # --- Optional: set if you have an OpenAI key ---
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini

          # --- Required for sending (transactional mode) ---
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          SENDER_NAME: "Daily ERP Brief"
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}

          # --- App settings ---
          TIMEZONE: America/New_York
          SEND_MODE: transactional         # keep as-is (you didn't set a Brevo list)
          MIN_ITEMS_TO_SEND: 1             # skip send if 0 items
          # VIEW_URL_BASE not required; pipeline has a safe default
        run: |
          set -x
          python -V
          python pipeline.py

      - name: Commit & publish archive
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p out
          TODAY=$(date -u +"%Y-%m-%d")
          # Make today's issue the landing page for "View in browser"
          if [ -f "out/${TODAY}.html" ]; then
            cp "out/${TODAY}.html" "out/index.html" || true
          fi
          # Only commit when /out changed
          if git status --porcelain | grep -q " out/"; then
            git add out/*.html || true
            git commit -m "Auto: publish daily issue"
            git push
          else
            echo "No changes to publish."
          fi
