name: Daily Newsletter
on:
  schedule:
    - cron: "15 11 * * *"   # 07:15 America/New_York (11:15 UTC)
  workflow_dispatch:

# allow this workflow to push commits (for the archive files in /out)
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          SENDER_NAME: "Daily ERP Brief"
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          TIMEZONE: America/New_York
          # switch to 'campaign' if you want to send to a Brevo list via Campaigns API
          SEND_MODE: ${{ vars.SEND_MODE || 'transactional' }}
          BREVO_LIST_ID: ${{ secrets.BREVO_LIST_ID }}
          # set this to your GitHub Pages base URL (e.g. https://you.github.io/repo/)
          VIEW_URL_BASE: ${{ vars.VIEW_URL_BASE || '' }}
          MIN_ITEMS_TO_SEND: 1
        run: |
          python pipeline.py

      - name: Commit & publish archive
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p out
          # Make latest issue the index for "View in browser"
          TODAY=$(date -u +"%Y-%m-%d")
          if [ -f "out/${TODAY}.html" ]; then
            cp "out/${TODAY}.html" "out/index.html"
          fi
          if git status --porcelain | grep -q "out/"; then
            git add out/*.html || true
            git commit -m "Auto: publish daily issue"
            git push
          else
            echo "No changes to publish."
          fi
