name: Daily Newsletter
on:
  schedule:
    - cron: "15 11 * * *"   # 07:15 America/New_York (11:15 UTC)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          SENDER_NAME: "Daily ERP Brief"
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          TIMEZONE: America/New_York
          MAX_ITEMS: 15
        run: |
          python pipeline.py
      - name: Commit & publish archive
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add out/*.html || true
          git commit -m "Auto: publish daily issue" || echo "No changes"
          git push
